# Generated by Django 4.2 on 2026-04-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
    ]
