# Generated by Django 4.2 on 2026-04-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
