# Generated by Django 4.2 on 2026-04-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_db", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="django_db_u_email_dc6c45_idx"),
        ),
    ]
